### ISSUE TITLE
How to get dev started

### ISSUE THREAD

**Issue by TimPietrusky** [funwithtriangles/instatrip#4]
I want to use the project to add my own shaders as masks onto my face. In order to do this I need to setup the project locally to make my changes. In this issue I try to summarize all the things that are needed to get started:

## Setup

* Clone the repo
* Install dependencies with `npm install`

## Dev

* Start the dev server: `npm run dev`

-> This is causing an error as the server requires a cert in `./certs/key.pem`

Quickfix: In `webpack.dev.js` you have to comment the lines 20 to 23. 

* Then you can run `npm run dev` again but see this error

```ERROR in unable to locate 'test-video' at '/Volumes/finalspace/dev/js/instatrip/test-video'```

* This is actually mentioned in the README, so create the folder `test-video` in the root-folder
* Then you can run `npm run dev` again but see this error

```ERROR in unable to locate 'test-video' at '/Volumes/finalspace/dev/js/instatrip/test-video/**/*'```

* So next was to find a video that is supported, so I created one using `Photo Booth` (mac) called `tim_webcam.mov` and added it into `test-video`
* Then you can run `npm run dev` again and see that the video is now added BUT it will still show the content of the webcam, not the test-video

-> Why is the video enforced for the dev-server, but it is not used? 

* In order to use the test-video, you have to edit `settings.ts` and replace `fakeCam: false`  with `fakeCam: 'tim_webcam.mov'`

THEN I can finally see the result.

**Comment by funwithtriangles** [comment]
Thanks for documenting all of this! I hadn't considered the fact that the missing video would break things even if you're not using it. I'll move some of these points over to the README.

**Comment by funwithtriangles** [comment]
I'm pretty sure this is all covered in the updated readme, so hopefully it's a little less painful if anyone else wants to play with it!

**Comment by TimPietrusky** [comment]
@funwithtriangles thank you very much!
